--- This file is generated by ava-x2l.exe,
--- Don't change it manaully.
--- @copyright Lilith Games, Project Da Vinci(Avatar Team)
--- @see Official Website: https://www.projectdavinci.com/
--- @see Dev Framework: https://github.com/lilith-avatar/avatar-ava
--- @see X2L Tool: https://github.com/lilith-avatar/avatar-ava-xls2lua
--- source file: ./Xls/PlayerActState.xlsx

local PlayerActStateXls = {
    [1] = {
        ID = 1,
        Name = 'Idle',
        NextName = 'Idle',
        Dur = 0.0
    },
    [2] = {
        ID = 2,
        Name = 'Walk',
        NextName = 'Walk',
        Dur = 0.0
    },
    [3] = {
        ID = 3,
        Name = 'Run',
        NextName = 'Run',
        Dur = 0.0
    },
    [4] = {
        ID = 4,
        Name = 'Jump',
        NextName = 'Idle',
        Dur = 0.6
    },
    [5] = {
        ID = 5,
        Name = 'Fly',
        NextName = 'Fly',
        Dur = 0.0
    },
    [6] = {
        ID = 6,
        Name = 'SwimIdle',
        NextName = 'SwimIdle',
        Dur = 0.0
    },
    [7] = {
        ID = 7,
        Name = 'Swimming',
        NextName = 'Swimming',
        Dur = 0.0
    }
}

return PlayerActStateXls
